// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBX96wKk8FonrCcoEBcUr6DON1JqGlq_io',
//     appId: '1:809516278463:web:9153dff54efb28608f9c0a',
//     messagingSenderId: '809516278463',
//     projectId: 'travelbusan',
//     authDomain: 'travelbusan.firebaseapp.com',
//     storageBucket: 'travelbusan.firebasestorage.app',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCEAhMi2-ZRyHIh3-2uERXaZrsuBmWxogw',
//     appId: '1:809516278463:android:340d352e1e863fd08f9c0a',
//     messagingSenderId: '809516278463',
//     projectId: 'travelbusan',
//     storageBucket: 'travelbusan.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAf2FQhg4qgw_svp_zvxpQcfuLPHNOabnc',
//     appId: '1:809516278463:ios:6763c84c7d6f76f78f9c0a',
//     messagingSenderId: '809516278463',
//     projectId: 'travelbusan',
//     storageBucket: 'travelbusan.firebasestorage.app',
//     iosBundleId: 'com.kyungsung.capstone',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAf2FQhg4qgw_svp_zvxpQcfuLPHNOabnc',
//     appId: '1:809516278463:ios:311495ff9fa6f32d8f9c0a',
//     messagingSenderId: '809516278463',
//     projectId: 'travelbusan',
//     storageBucket: 'travelbusan.firebasestorage.app',
//     iosBundleId: 'com.example.capstone',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBX96wKk8FonrCcoEBcUr6DON1JqGlq_io',
//     appId: '1:809516278463:web:534890b8ac815cb38f9c0a',
//     messagingSenderId: '809516278463',
//     projectId: 'travelbusan',
//     authDomain: 'travelbusan.firebaseapp.com',
//     storageBucket: 'travelbusan.firebasestorage.app',
//   );
// }
